version: '3.7'
services:
    dbmysqlbackbone:
        container_name: db_mysql_backbone-container
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_TCP_PORT: ${MYSQL_PORT}
            MYSQL_UNIX_PORT: ${MYSQL_PORT}
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./localfolder/mysql:/var/lib/mysql
            - ./localfolder/logs/mysql:/var/log/mysql
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        networks:
            - backbonenet

    go_backbone:
        image: handokowae/go-back-bone-dapo:1.10-linux-amd64
        container_name: 'go-container-backbone'
        environment:
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_HOST: ${MYSQL_HOST}
            DB_HOST: ${MYSQL_HOST}
            DB_PORT: ${MYSQL_PORT}
            DB_USERNAME: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}
            APP_PORT: ${GO_API_APP_PORT}
            USERNAME_DAPO: ${USERNAME_DAPO}
            PASSWORD_DAPO: ${PASSWORD_DAPO}
            API_TOKEN_DAPO: ${API_TOKEN_DAPO}
            URL_DAPO: ${URL_DAPO}
        restart: always
        ports:
            - ${GO_API_APP_PORT}:${GO_API_APP_PORT}
            #volumes:
            #- ./localfolder/www/public/upload:/app/upload
            #- ./localfolder/www/public/uploads/peserta/user:/app/uploads/user
            #- ./localfolder/www/public/uploads/peserta/slider:/app/uploads/slider
            #- ./localfolder/www/public/uploads/panduan:/app/uploads/panduan
            #user: "${UID}:${GID}"
        depends_on:
            - dbmysqlbackbone
        networks:
            - backbonenet

    phpmyadmin_backbone:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'phpmyadmin-container-mysql-backbone'
        networks:
            - backbonenet
        environment:
            PMA_HOST: ${MYSQL_HOST}
            PMA_PORT: ${MYSQL_PORT}
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 8065:80
        volumes:
            - ./localfolder/sessions:/sessions

networks:
    backbonenet:
        driver: bridge
